name: Discord Bot Workflow

# When to trigger the workflow
on:
  push:
    branches:
      - main  # Change 'main' to your branch if needed

jobs:
  run-bot:
    runs-on: ubuntu-latest  # Use an Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Fetch the repository code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10  # Use the version your bot requires

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        python bot.py
